---
title: "r3pgn"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Manual for the r3pgn package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
abstract: "adsf". 
\n \n \n"

---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5, warning=FALSE, cache = F)
```

```{r, echo = F, message = F}
set.seed(123)
library(threePGN)
library(dplyr)
library(ggplot2)
```

# Run the model
```{r}
firstRun <- r3pgn(siteData = data_site[1:3,], climate = data_climate, parameters = data_param[,2], outputs = c(1:5,
  10:12, 26:27))
```

# Visualiza the output
```{r}
varnames <- firstRun$vars

# tranform output to the long format
matrix(firstRun$output, ncol = firstRun$noOfSites, byrow = F) %>%
  data.frame() %>%
  mutate(variable = rep(varnames, each = firstRun$nMonths),
         id = rep(1:firstRun$nMonths, times = length(varnames))) %>%
  tidyr::gather(site, value, -variable, -id) %>%
  tidyr::spread(variable, value) %>%
  select(-id) %>%
  tidyr::gather(variable, value, -site, -StandAge) ->
  firstRun_long

# visualize the run
firstRun_long %>%
  ggplot()+
  geom_line(aes(StandAge, value, colour = site))+
  facet_wrap(~variable, scales = 'free_y') +
  theme_bw()
```

